### ISSUE TITLE
请问大佬 glide加载多语言的drawable的问题解决了吗

### ISSUE THREAD

**Issue by zhupengxiang** [JsonCooler/Jpermission#1]
请问大佬 glide加载多语言的drawable的问题解决了吗

**Comment by JsonCooler** [comment]
没有 后面我直接用的原生方法 在代码里面 用的setImageResource()方法去加载图片




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JsonCooler/Jpermission"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月5日(星期二) 晚上7:40
收件人:&nbsp;"JsonCooler/Jpermission"<Jpermission@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[JsonCooler/Jpermission] 请问大佬 glide加载多语言的drawable的问题解决了吗 (#1)





 
请问大佬 glide加载多语言的drawable的问题解决了吗

**Comment by zhupengxiang** [comment]
好吧   我最后也是直接设置的  感谢
